export const LOGIN_USER = 'SYSTEM/LOGIN';
export const LOGOUT_USER = 'SYSTEM/LOGOUT';

export const SET_TIME_INTERVAL = 'SYSTEM/SET_TIME_INTERVAL';
export const GET_TIME_INTERVAL = 'SYSTEM/GET_TIME_INTERVAL';
