export const LOGIN_USER = 'SYSTEM/LOGIN';
export const LOGOUT_USER = 'SYSTEM/LOGOUT';

export const SET_TIME_INTERVAL = 'SYSTEM/SET_TIME_INTERVAL';
export const GET_TIME_INTERVAL = 'SYSTEM/GET_TIME_INTERVAL';

export const SET_COUNTDOWN_ID = 'SYSTEM/SET_COUNTDOWN_ID';
export const GET_COUNTDOWN_ID = 'SYSTEM/GET_COUNTDOWN_ID';

export const LOAD_QUIZ = 'DATA/LOAD_QUIZ';
export const CLEAR_QUIZ = 'DATA/CLEAR_QUIZ';
export const SET_ANSWER_VALUE = 'DATA/SET_ANSWER_VALUE';
export const SET_CURRENT_QUESTION_INDEX = 'DATA/SET_CURRENT_QUESTION_INDEX';
export const INCREASE_QUESTION_INDEX = 'DATA/INCREASE_QUESTION_INDEX';
export const DECREASE_QUESTION_INDEX = 'DATA/DECREASE_QUESTION_INDEX';
export const MOVETO_LAST_QUESTION_INDEX = 'DATA/MOVE_TO_LAST_QUESTION_INDEX';
export const CLEAR_QUESTION_STATES = 'DATA/CLEAR_QUESTION_STATES';
export const ADD_QUESTION = 'DATA/ADD_QUESTION';
export const SUBMIT_QUESTION = 'DATA/SUBMIT_QUESTION';
export const UPLOAD_QUESTION = 'DATA/UPLOAD_QUESTION';
export const UNSUBMIT_QUESTION = 'DATA/UNSUBMIT_QUESTION';
